# Generated by Django 4.1.13 on 2024-01-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_of_page',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='publish_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.IntegerField(null=True),
        ),
    ]
